{% set name = "jhub-apps" %}
{% set version = "2024.10.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jhub_apps-{{ version }}.tar.gz
  sha256: 43118d3dce2ed4fe385a0d399770f13220da267cd60b1bc4e3968d3bb78db55c

build:
  entry_points:
    - japps = jhub_apps.main:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - hatchling
    - hatch
    - requests
    - fastapi
    - uvicorn
    - jupyterhub
    - jupyter
    - plotlydash-tornado-cmd
    - bokeh-root-cmd
    - jhsingle-native-proxy ==0.8.2
    - panel
    - bokeh
    - traitlets
    - pyjwt
    - python-multipart
    - python-slugify
    - cachetools
    - structlog
    - conda-project

test:
  imports:
    - jhub_apps
  commands:
    - pip check
    - japps --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/nebari-dev/jhub-apps/
  summary: JupyterHub Apps
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aktech
    - dcmcand
    - costrouc
